{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "da-manager.serviceAccountName" . }}
  labels:
    {{- include "da-manager.labels" . | nindent 4 }}
{{- end }}
