import type { DAData } from "@/types/da.types";

// Données initiales vides avec la structure EXACTE du DA
export const initialData: DAData = {
  cadre1_ProjetActeurs: {
    nomDuProjet: "",
    contexteProjetApplicatif: "",
    objectifsProjetApplicatif: "",
    enjeuxProjetApplicatif: "",
    // Planning projet : 3 lignes FIXES
    planningProjet: [
      { version: "V1", date: "", commentaires: "" },
      { version: "V2", date: "", commentaires: "" },
      { version: "V3", date: "", commentaires: "" },
    ],
    // Acteurs du projet : rôles FIXES
    acteursDuProjet: [
      { role: "MOA", nom: "", fonction: "", entite: "" },
      { role: "AMOA", nom: "", fonction: "", entite: "" },
      { role: "ETUDE", nom: "", fonction: "", entite: "" },
      { role: "MOE", nom: "", fonction: "", entite: "" },
      { role: "AMOE", nom: "", fonction: "", entite: "" },
      { role: "INTEGRATEUR", nom: "", fonction: "", entite: "" },
      { role: "ARCHITECTE SI", nom: "", fonction: "", entite: "" },
      { role: "INTEGRATION", nom: "", fonction: "", entite: "" },
      { role: "PRODUCTION", nom: "", fonction: "", entite: "" },
    ],
    // Acteurs métiers : tableau DYNAMIQUE avec lignes vides pré-remplies
    acteursMetiersDuSIApplicatif: [
      { profilsActeurs: "", nombreUtilisateursM: "0", nombreUtilisateursR: "0", nombreUtilisateursE: "0", nombreUtilisateursP: "0" },
      { profilsActeurs: "", nombreUtilisateursM: "0", nombreUtilisateursR: "0", nombreUtilisateursE: "0", nombreUtilisateursP: "0" },
      { profilsActeurs: "", nombreUtilisateursM: "0", nombreUtilisateursR: "0", nombreUtilisateursE: "0", nombreUtilisateursP: "0" },
      { profilsActeurs: "", nombreUtilisateursM: "0", nombreUtilisateursR: "0", nombreUtilisateursE: "0", nombreUtilisateursP: "0" },
      { profilsActeurs: "", nombreUtilisateursM: "0", nombreUtilisateursR: "0", nombreUtilisateursE: "0", nombreUtilisateursP: "0" },
      { profilsActeurs: "", nombreUtilisateursM: "0", nombreUtilisateursR: "0", nombreUtilisateursE: "0", nombreUtilisateursP: "0" },
      { profilsActeurs: "", nombreUtilisateursM: "0", nombreUtilisateursR: "0", nombreUtilisateursE: "0", nombreUtilisateursP: "0" },
      { profilsActeurs: "", nombreUtilisateursM: "0", nombreUtilisateursR: "0", nombreUtilisateursE: "0", nombreUtilisateursP: "0" },
    ],
  },
  cadre2_FonctionnalitesDonnees: {
    // Tableaux avec lignes vides pré-remplies (environ 10 lignes comme dans le DA)
    fonctionnalitesDuSIApplicatif: Array(10).fill(null).map(() => ({ fonctionnalite: "", M: false, R: false, E: false, P: false })),
    donneesMetierDuSIApplicatif: Array(10).fill(null).map(() => ({ donnee: "", M: false, R: false, E: false, P: false })),
    fichiersMetiersDuSIApplicatif: Array(8).fill(null).map(() => ({ fichier: "", M: false, R: false, E: false, P: false })),
    referentielsDonneesHorsSI: Array(6).fill(null).map(() => ({ referentiel: "", modeEchange: "", siSource: "", M: false, R: false, E: false, P: false })),
    sensibiliteDesDonnees: {
      NIR: "",
      medicales: "",
      viePrivee: "",
      etatCivil: "",
      identite: "",
      viePersonnelle: "",
      biometrique: "",
      vieProfessionnelle: "",
      mecanismeFraude: "",
      mouvementsSalariaux: "",
      santeEconomique: "",
      patrimoine: "",
      appartenanceSyndicale: "",
      justice: "",
      adressePostale: "",
      faillesVulnerabilite: "",
      publicDonnees: "",
      editoriaux: "",
      publicationExtranet: "",
      campagneDeCom: "",
      statistiquesPubliables: "",
      autres: "",
    },
    servicesUtilisesParApplication: [
      { service: "Messagerie (Exchange)", modeEchange: "", siSource: "", M: false, R: false, E: false, P: false },
      { service: "Annuaire (Active directory)", modeEchange: "", siSource: "", M: false, R: false, E: false, P: false },
      { service: "SIG (ArcGIS)", modeEchange: "", siSource: "", M: false, R: false, E: false, P: false },
      { service: "Décisionnel (BI)", modeEchange: "", siSource: "", M: false, R: false, E: false, P: false },
      { service: "Transfert de fichiers (CFT)", modeEchange: "", siSource: "", M: false, R: false, E: false, P: false },
    ],
  },
  cadre3_ContraintesVolumetrie: {
    contraintesLegales: "",
    contraintesMetiers: "",
    dependancesAvecDautresSI: Array(6).fill(null).map(() => ({ systemeInformation: "", fournisseur: false, consommateur: false })),
    dependancesAvecLePosteDeTravail: "",
    niveauUtilisabiliteSecuriteEnModeTablette: {
      modeConnecte: "Néant",
      modeDeconnecte: "Néant",
      precisions: "",
    },
    niveauUtilisabiliteSecuriteEnModeSmartphone: {
      modeConnecte: "Néant",
      modeDeconnecte: "Néant",
      precisions: "",
    },
    mobile: {
      tabletteMinistere: 0,
      tablettePersonnel: 0,
      smartphoneMinistere: 0,
      smartphonePersonnel: 0,
    },
    volumetrieDonneesDuSIApplicatif: {
      d1_NombreEnregistrementsARecuperer: "",
      d2_NombreEnregistrementsParAn: "",
      d3_TailleMoyenneEnregistrementKO: "",
      d4_NombreAnneesEnregistrementsEnBaseBDD: "",
      d5_VolumeBDDInitialGO: "",
      d6_VolumeBDDActuelGO: "",
      d7_VolumeBDDTotalGO: "",
      commentaires: "",
    },
    volumetrieFichiersDuSIApplicatif: {
      f1_NombreDeFichiersARecuperer: "",
      f2_NombreDeFichiersParAn: "",
      f3_TailleMoyenneDunFichierMO: "",
      f4_NombreAnneesFichiersEnFileSystemFS: "",
      f5_VolumeFSInitialGO: "",
      f6_VolumeFSActuelGO: "",
      f7_VolumeFSTotalGO: "",
    },
    reductionVolumeDonneesEtFichiers: {
      purgeDonneesDansBDDApplicatif: false,
      purgeFichiersDansFSApplicatif: false,
      archivageDonneesHorsApplicatif: false,
      archivageFichiersHorsApplicatif: false,
    },
  },
  cadre4_ExigencesContextuelles: {
    echelleDICT_EBIOS_1a4_GlobalSI: {
      exigenceDisponibilite_NiveauFront: 1,
      exigenceDisponibilite_PrecisionsFront: "",
      exigenceDisponibilite_NiveauBack: 1,
      exigenceDisponibilite_PrecisionsBack: "",
      exigenceIntegrite_NiveauFront: 1,
      exigenceIntegrite_PrecisionsFront: "",
      exigenceIntegrite_NiveauBack: 1,
      exigenceIntegrite_PrecisionsBack: "",
      exigenceConfidentialite_NiveauFront: 1,
      exigenceConfidentialite_PrecisionsFront: "",
      exigenceConfidentialite_NiveauBack: 1,
      exigenceConfidentialite_PrecisionsBack: "",
      exigenceTracabilite_NiveauFront: 1,
      exigenceTracabilite_PrecisionsFront: "",
      exigenceTracabilite_NiveauBack: 1,
      exigenceTracabilite_PrecisionsBack: "",
    },
    echelleIMPACT_EBIOS_GlobalSI: {
      domaine: "",
      niveau: "",
      description: "",
    },
    exigencePREUVE_ParFonctionnalite: Array(5).fill(null).map(() => ({ fonctionnalite: "", descriptionExigencePreuve: "" })),
    exigencesSurLesAccesUtilisateurs: "",
    exigenceDisponibilite: "",
    exigenceIntegrite: "",
    exigenceConfidentialite: "",
    exigenceTracabilite: "",
    garantieDeService: {
      planDeContinuiteActivite_PCA: "",
      planDeRepriseActivite_PRA: "",
      perteDeDonneesNonAdmissible: "",
      dureMaximaleInterruptionAdmissible_DMIA: "",
    },
    periodesApplicatives: Array(3).fill(null).map(() => ({ periode: "", dateDebut: "", dateFin: "", nuc_NombreUtilisateursConnectes: "", nrs_NombreRequetesSimultaneesParSec: "" })),
    tempsDeReponse: {
      affichagePageAccueil_PeriodeStandard: "",
      affichagePageAccueil_PeriodeDeCharge: "",
      affichagePageSimple_PeriodeStandard: "",
      affichagePageSimple_PeriodeDeCharge: "",
      affichagePageComplexe_PeriodeStandard: "",
      affichagePageComplexe_PeriodeDeCharge: "",
      traitementRequeteSimple_PeriodeStandard: "",
      traitementRequeteSimple_PeriodeDeCharge: "",
      traitementRequeteComplexe_PeriodeStandard: "",
      traitementRequeteComplexe_PeriodeDeCharge: "",
      precisions: "",
    },
    traitementsAutomatises: Array(4).fill(null).map(() => ({ batchsApplicatifs: "", plage: "", frequence: "", impactMetier: "", impactCharge: "" })),
  },
  cadre5_ArchitectureActeurs: {
    description: "",
    schemaActeurs: "",
    acteursConsommateurs: [],
    acteursFournisseurs: [],
  },
  cadre6_ArchitectureFonctionnelle: {
    description: "",
    schemaArchitectureFonctionnelle: "",
    blocsFonctionnels: [],
    conventionFlux: "",
  },
  cadre7_ArchitectureApplicative: {
    description: "",
    schemaArchitectureApplicative: "",
    pilesComposants: [],
  },
  cadre8_ArchitectureTechnique: {
    description: "",
    schemaArchitectureTechnique: "",
    notes: "",
  },
  cadre9_ServeursComposants: {
    serveurs: Array(4).fill(null).map(() => ({
      nomServeur: "",
      type: "Machine Virtuelle" as const,
      role: "",
      vCPU: 0,
      ramGO: 0,
      composantsLogiciels: Array(5).fill(null).map(() => ({
        categorie: "",
        composant: "",
        version: "",
        role: "",
      })),
    })),
  },
  cadre10_MatricesFlux: {
    fluxApplicatifs: Array(10).fill(null).map(() => ({
      numeroFlux: "",
      source: "",
      destination: "",
      protocole: "",
      commentaires: "",
    })),
  },
  cadre11_Dimensionnement: {
    justificationsPDMA_DMIA_Performances: {
      perteDeDonneesMaximaleAdmissible: "",
      dureeMaximaleInterruptionAdmissible: "",
      performancesApplicatives: "",
    },
    justificationsAllocationsRessourcesMaterielles: {
      nombreCPU: "",
      nombreServeurs: "",
      detailsCalculs: "",
    },
  },
  cadre12_URLs: {
    urls: Array(5).fill(null).map(() => ({
      libelleURL: "",
      acteurAppelant: "",
      ressourceAppelee: "",
      fonctionnaliteOuServiceFourni: "",
      donneesTransitent: "",
      precisions: "",
    })),
  },
  annexe_SuiviChangements: {
    versionnage: "1.0.0",
    changements: Array(3).fill(null).map(() => ({
      version: "",
      date: "",
      demandeurChangement: "",
      rapporteurChangement: "",
      descriptionDetaillee: "",
    })),
  },
};
